<a href="https://colab.research.google.com/github/CakeNuthep/Super_AI/blob/master/8_Puzzle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **8-Puzzle**

> Use BFS Algorithm









In [39]:
import numpy as np

In [264]:
WIDTH_PUZZLE = 3
HEIGHT_PUZZLE = 3
history = {}
queue = []
game_8_puzzle_epected = (1,2,3,4,5,6,7,8,0)
game_8_puzzle_start = (0,1,2,3,4,5,6,7,8)
game_8_puzzle_start_arr =  np.array(game_8_puzzle_start)
game_8_puzzle_start_arr = game_8_puzzle_start_arr.reshape([HEIGHT_PUZZLE,WIDTH_PUZZLE])

In [250]:
count_step = 0
def step():
  isEmpty = len(queue) == 0
  if not isEmpty:
    node = queue.pop(0)
    index_row,index_col = findZero(node)
    list_next_node = getPossibleNodeFromNear(node,index_row,index_col)
    
    for next_node in list_next_node:
      if not hasInHistory(next_node):
        queue.append(next_node)
        saveHistory(node,next_node,count_step)


def findZero(node):
  for index_row,row_data in enumerate(node):
    for index_col,data in enumerate(row_data):
      if data == 0:
        return (index_row,index_col)

def findExpect():
  if game_8_puzzle_epected in history.keys():
      return True
  return False

def findIndexNear(index_row,index_col):
  steps_near = (0,1,-1)
  list_index_near = []
  for step_row in steps_near:
    for step_col in steps_near:
      isDiagonal = abs(step_row) == 1 and abs(step_col) == 1
      if not isDiagonal and (step_row != 0 or step_col != 0):
        next_index_row = index_row + step_row
        next_index_col = index_col + step_col
        is_next_index_in_row = next_index_row >= 0 and next_index_row < HEIGHT_PUZZLE
        is_next_index_in_col = next_index_col >= 0 and next_index_col < WIDTH_PUZZLE
        if(is_next_index_in_row and is_next_index_in_col):
          list_index_near.append((next_index_row,next_index_col))
  return list_index_near

def getPossibleNodeFromNear(node,index_zero_row,index_zero_col):
  list_index_near = findIndexNear(index_zero_row,index_zero_col)
  list_next_node = []
  for index_near in list_index_near:
    next_node = node.copy()
    next_node[index_zero_row,index_zero_col] = node[index_near[0],index_near[1]]
    next_node[index_near[0],index_near[1]] = node[index_zero_row,index_zero_col]
    list_next_node.append(next_node)

  return list_next_node
      

def saveHistory(node,next_node,count_step):
  flat_next_node = next_node.flatten()
  tup_next_node = tuple(flat_next_node)
  if not hasInHistory(next_node):
    flat_node = node.flatten()
    tup_node = tuple(flat_node)
    history[tup_next_node] = {}
    history[tup_next_node] = {"prevNode":tup_node,"countStep":count_step}

def hasInHistory(node):
  flat_node = node.flatten()
  tup_node = tuple(flat_node)
  if tup_node in history.keys():
    return True
  return False

def getBestPath():
  list_path = []
  if findExpect():
    node = history[game_8_puzzle_epected]
    list_path.append(node)
    findStart = False
    while not findStart:
      if  node["prevNode"] in history.keys():
        node = history[node["prevNode"]]
        list_path.append(node)
        findStart = checkIsSameTuple(node["prevNode"],game_8_puzzle_start)
  return list_path

def checkIsSameTuple(data1,data2):
  if data1 is not None and data2 is not None:
    for index in range(len(data1)):
      if data1[index] != data2[index]:
        return False
  return True




In [265]:
history = {}
queue = []
count_step = 0
queue.append(game_8_puzzle_start_arr)
flat_node_start = game_8_puzzle_start_arr.flatten()
tup_node_start = tuple(flat_node_start)
history[tup_node_start] = {}
history[tup_node_start] = {"prevNode":None,"countStep":0}

In [266]:
isEmpty = len(queue) == 0
foundExpect = False
epoc = 10000
while (not isEmpty) and (not foundExpect):
  count_step+=1
  if count_step % epoc == 0:
    print(f"countStep:{count_step}")
  step()
  foundExpect = findExpect()



countStep:10000
countStep:20000
countStep:30000
countStep:40000
countStep:50000
countStep:60000


In [267]:

listBestPath = getBestPath()
listBestPath.reverse()
listBestPath

for show_node in listBestPath:
  index = 0
  data = show_node["prevNode"]
  if data is not None:
    print(np.array(data).reshape([HEIGHT_PUZZLE,WIDTH_PUZZLE]))
  
  print()
  print("||")
  print("V")
  print()
print(np.array(game_8_puzzle_epected).reshape([HEIGHT_PUZZLE,WIDTH_PUZZLE]))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

||
V

[[1 0 2]
 [3 4 5]
 [6 7 8]]

||
V

[[1 4 2]
 [3 0 5]
 [6 7 8]]

||
V

[[1 4 2]
 [0 3 5]
 [6 7 8]]

||
V

[[1 4 2]
 [6 3 5]
 [0 7 8]]

||
V

[[1 4 2]
 [6 3 5]
 [7 0 8]]

||
V

[[1 4 2]
 [6 3 5]
 [7 8 0]]

||
V

[[1 4 2]
 [6 3 0]
 [7 8 5]]

||
V

[[1 4 2]
 [6 0 3]
 [7 8 5]]

||
V

[[1 4 2]
 [0 6 3]
 [7 8 5]]

||
V

[[1 4 2]
 [7 6 3]
 [0 8 5]]

||
V

[[1 4 2]
 [7 6 3]
 [8 0 5]]

||
V

[[1 4 2]
 [7 0 3]
 [8 6 5]]

||
V

[[1 0 2]
 [7 4 3]
 [8 6 5]]

||
V

[[1 2 0]
 [7 4 3]
 [8 6 5]]

||
V

[[1 2 3]
 [7 4 0]
 [8 6 5]]

||
V

[[1 2 3]
 [7 4 5]
 [8 6 0]]

||
V

[[1 2 3]
 [7 4 5]
 [8 0 6]]

||
V

[[1 2 3]
 [7 4 5]
 [0 8 6]]

||
V

[[1 2 3]
 [0 4 5]
 [7 8 6]]

||
V

[[1 2 3]
 [4 0 5]
 [7 8 6]]

||
V

[[1 2 3]
 [4 5 0]
 [7 8 6]]

||
V

[[1 2 3]
 [4 5 6]
 [7 8 0]]
